package com.coam.pdfvalidator.infrastructure.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;

import org.springframework.beans.factory.ObjectProvider;
import org.springframework.boot.info.BuildProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Publishes the OpenAPI {@code info} block springdoc uses to build
 * {@code /v3/api-docs} and {@code /swagger-ui.html}.
 *
 * <p>The version is read from {@link BuildProperties} (populated from
 * {@code target/classes/META-INF/build-info.properties}, generated by the
 * {@code spring-boot-maven-plugin}'s {@code build-info} goal, bound to the
 * {@code prepare-package} phase). That phase runs on {@code mvn package}/
 * {@code verify}, but not on a bare {@code mvn test} or an exploded {@code
 * spring-boot:run} without a preceding package/verify -- so {@link
 * BuildProperties} may legitimately be absent (fetched via {@link
 * ObjectProvider}, never required), in which case the version falls back to
 * a constant kept in sync with {@code pom.xml}'s {@code <version>}.
 */
@Configuration
public class OpenApiConfiguration {

    /** Kept in sync with pom.xml's project version; used only when BuildProperties is unavailable. */
    private static final String FALLBACK_VERSION = "0.1.0-SNAPSHOT";

    @Bean
    public OpenAPI pdfValidatorOpenApi(ObjectProvider<BuildProperties> buildProperties) {
        BuildProperties properties = buildProperties.getIfAvailable();
        String version = properties != null ? properties.getVersion() : FALLBACK_VERSION;

        return new OpenAPI().info(new Info()
                .title("PDF Inspector & Signature Verifier API")
                .description("Single-pass technical/forensic audit of a PDF document: signature integrity "
                        + "(PAdES/CMS), post-signature modification detection, RFC 3161 timestamps, X.509 chain "
                        + "trust, optional OCSP/CRL revocation, PDF/A-1b conformance and physical page properties.")
                .version(version)
                .license(new License().name("GPL-3.0").url("https://www.gnu.org/licenses/gpl-3.0.html")));
    }
}
