package com.coam.pdfvalidator.tools.tsl;

import java.nio.charset.StandardCharsets;
import java.security.cert.CertificateEncodingException;
import java.security.cert.X509Certificate;
import java.util.Base64;
import java.util.List;
import java.util.SortedMap;
import java.util.TreeMap;
import java.util.stream.Collectors;

/**
 * Renders the whole bundled trust store directory in memory: one PEM
 * {@code .crt} per anchor, {@code index.txt} (the list the runtime loads)
 * and {@code SOURCES.md} (provenance). Every byte depends only on the two
 * verified lists, never on when the tool ran, so an unchanged list yields an
 * identical directory.
 */
final class TrustStoreRenderer {

    static final String INDEX = "index.txt";
    static final String SOURCES = "SOURCES.md";

    private TrustStoreRenderer() {
    }

    static SortedMap<String, String> render(VerifiedTrustedList lotl, VerifiedTrustedList tsl, List<Anchor> anchors) {
        SortedMap<String, String> files = new TreeMap<>();
        StringBuilder index = new StringBuilder()
                .append("# Generated by com.coam.pdfvalidator.tools.tsl.TslSync from ")
                .append(tsl.source()).append(" (TSLSequenceNumber ").append(tsl.list().sequenceNumber())
                .append("). Do not edit: re-run ./mvnw -q -Ptsl-sync\n");
        for (Anchor anchor : anchors) {
            files.put(anchor.fileName(), pem(anchor.certificate()));
            index.append(anchor.fileName()).append('\n');
        }
        files.put(INDEX, index.toString());
        files.put(SOURCES, sources(lotl, tsl, anchors));
        return files;
    }

    static String pem(X509Certificate certificate) {
        try {
            String body = Base64.getMimeEncoder(64, "\n".getBytes(StandardCharsets.US_ASCII))
                    .encodeToString(certificate.getEncoded());
            return "-----BEGIN CERTIFICATE-----\n" + body + "\n-----END CERTIFICATE-----\n";
        } catch (CertificateEncodingException e) {
            throw new IllegalStateException("Cannot encode an anchor certificate", e);
        }
    }

    private static String sources(VerifiedTrustedList lotl, VerifiedTrustedList tsl, List<Anchor> anchors) {
        long timestampServices = anchors.stream().filter(anchor -> "TSA/QTST".equals(anchor.kind())).count();
        StringBuilder md = new StringBuilder();
        md.append("# Bundled trust anchors — provenance\n\n")
                .append("Generated by the maintainer tool `com.coam.pdfvalidator.tools.tsl.TslSync` ")
                .append("(`./mvnw -q -Ptsl-sync`). **Do not edit this directory by hand**: every file in it ")
                .append("(the `.crt` anchors, `index.txt` and this `SOURCES.md`) is regenerated from the ")
                .append("official EU trusted lists below. The `.crt` files are PEM-encoded certificates.\n\n")
                .append("## Sources\n\n")
                .append("| List | URL | TSLSequenceNumber | ListIssueDateTime | NextUpdate | Signer certificate SHA-256 |\n")
                .append("|---|---|---|---|---|---|\n");
        sourceRow(md, "EU List of Trusted Lists (LOTL)", lotl);
        sourceRow(md, "Spanish Trusted List (ES TSL)", tsl);
        md.append("\n## How the lists are trusted\n\n")
                .append("- The LOTL signer certificate must be one of the six certificates announced by the ")
                .append("European Commission in the Official Journal (OJ C/2026/1944), pinned by SHA-256 in ")
                .append("`TslSync.LOTL_SIGNER_SHA256`.\n")
                .append("- The ES TSL is the one the verified LOTL points to (`OtherTSLPointer` with ")
                .append("`SchemeTerritory` `ES` and `MimeType` `application/vnd.etsi.tsl+xml`); its signer ")
                .append("certificate must be one of that pointer's `ServiceDigitalIdentities`.\n")
                .append("- Both signatures are enveloped XML signatures verified with the JDK (secure ")
                .append("validation on): exactly one `ds:Signature`, first `Reference` `URI=\"\"` with only the ")
                .append("enveloped-signature and canonicalization transforms, signer certificate valid at run ")
                .append("time, and `NextUpdate` still in the future.\n\n")
                .append("## Selection rules\n\n")
                .append("Only the current `ServiceInformation` of each ES TSL service counts (`ServiceHistory` ")
                .append("is ignored). A service's `X509Certificate` digital identities become anchors when:\n\n")
                .append("- `ServiceStatus` is `http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/granted`; and\n")
                .append("- `ServiceTypeIdentifier` is `http://uri.etsi.org/TrstSvc/Svctype/TSA/QTST` ")
                .append("(qualified timestamps), or `http://uri.etsi.org/TrstSvc/Svctype/CA/QC` usable for ")
                .append("electronic signatures: its `AdditionalServiceInformation` includes ")
                .append("`http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/ForeSignatures`, or a ")
                .append("qualifier is `http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/QCForESig`, or it ")
                .append("has no usage restriction at all (none of `ForeSignatures`, `ForeSeals`, ")
                .append("`ForWebSiteAuthentication`). CA/QC services only for seals and/or website ")
                .append("authentication are left out;\n")
                .append("- the certificate has not expired when the tool runs (`notAfter` in the future).\n\n")
                .append("Certificates listed by several services are bundled once (deduplicated by SHA-256).\n\n")
                .append("## Anchors (").append(anchors.size()).append(": ")
                .append(anchors.size() - timestampServices).append(" CA/QC, ")
                .append(timestampServices).append(" TSA/QTST)\n\n")
                .append("| File | TSP | Service | Type | Status since | Subject | SHA-256 | Not after |\n")
                .append("|---|---|---|---|---|---|---|---|\n");
        for (Anchor anchor : anchors) {
            md.append("| `").append(anchor.fileName()).append("` | ")
                    .append(cell(anchor.services().getFirst().providerName())).append(" | ")
                    .append(joined(anchor, TrustService::serviceName)).append(" | ")
                    .append(joined(anchor, service -> AnchorSelector.TSA_QTST.equals(service.type())
                            ? "TSA/QTST" : "CA/QC")).append(" | ")
                    .append(joined(anchor, service -> service.statusStartingTime().toString())).append(" | ")
                    .append(cell(anchor.certificate().getSubjectX500Principal().getName())).append(" | `")
                    .append(anchor.sha256()).append("` | ")
                    .append(anchor.certificate().getNotAfter().toInstant()).append(" |\n");
        }
        return md.toString();
    }

    private static void sourceRow(StringBuilder md, String name, VerifiedTrustedList verified) {
        md.append("| ").append(name).append(" | ").append(verified.source()).append(" | ")
                .append(verified.list().sequenceNumber()).append(" | ")
                .append(verified.list().issueDate()).append(" | ")
                .append(verified.list().nextUpdate()).append(" | `")
                .append(Fingerprints.sha256(verified.signer())).append("` |\n");
    }

    private static String joined(Anchor anchor, java.util.function.Function<TrustService, String> field) {
        return anchor.services().stream().map(field).map(TrustStoreRenderer::cell)
                .collect(Collectors.joining("<br>"));
    }

    private static String cell(String text) {
        return text.replace("\\", "\\\\").replace("|", "\\|").replace("\r", " ").replace("\n", " ");
    }
}
